### ISSUE TITLE
Problems with another model

### ISSUE THREAD

**Issue by Spectra456** [Kautenja/ios-semantic-segmentation#3]
Hey, what's up? Thank you for you application. Can you help me with one small issue? I'm just trying use my own model converted to CoreML in your app. It's have only 1 class. And I get this:
![img_0433](https://user-images.githubusercontent.com/31315447/47883513-53cbbd80-de3e-11e8-9e2e-f42566817156.PNG)
**P.S In my own app, this model is working.**

**Comment by Kautenja** [comment]
What exactly do you mean by one class? Do you mean your graph has pixelwise output with a single channel that's intended to go through a sigmoidal function followed by rounding (i.e, reducing to 0 or 1), or two channels intended to pass through a softmax function followed by ArgMax where one channel is a class and the other channel is something like "void" or "background"? Unless you've adjusted the color mapping, it looks like the model is producing 7 as the final output for each pixels which is odd for either of the described models. Could you share the CoreML description of the mode file?

**Comment by Spectra456** [comment]
> What exactly do you mean by one class? Do you mean your graph has pixelwise output with a single channel that's intended to go through a sigmoidal function followed by rounding (i.e, reducing to 0 or 1), or two channels intended to pass through a softmax function followed by ArgMax where one channel is a class and the other channel is something like "void" or "background"? Unless you've adjusted the color mapping, it looks like the model is producing 7 as the final output for each pixels which is odd for either of the described models. Could you share the CoreML description of the mode file?

**Comment by Spectra456** [comment]
<img width="777" alt="2018-11-02 14 02 20" src="https://user-images.githubusercontent.com/31315447/47911971-0f750780-dea8-11e8-95e0-5cfb653d6482.png">

**Comment by Kautenja** [comment]
ahh after looking the 0th label is actually red (code: 255, 0, 0) meaning that the ArgMax is correctly returning 0 for all your pixels (not 7 like i originally thought). Your model is producing a single channel output likely indicating that the outputs pass through a sigmoidal unit to produce a probability for each pixel. This is standard in binary classification problems, such as single class semantic segmentation like I imagine you're trying to perform. The codebase here expects categorical models opposed to binary ones and as such passes the final output tensor through ArgMax to extract an integer code representing the class label among a set (8 in this case) for each pixel. Because your model only has the single channel, ArgMax produces its index irrespective of value (i.e., 0 = red). You'd need to replace this operation with some form of rounding (i.e., multiply output1 by 2 and cast to integer) to reduce your network output to either 0 (background) or 1 (class label). Then you could use this to mask out a color image to produce the semantic map like shown in the README. Closing issue as the current behavior is expected and this repository only aims to provide a simple example for categorical semantic segmentation. Feel free to fork and introduce the changes to adapt your model though!

**Comment by Spectra456** [comment]
Okay, thank you!
